import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from scipy.stats import pearsonr, spearmanr
import argparse

# this script compares the results generated by indices_prediction.py, and
# produces bland-altman plots and statistics from the distributions of values


def analysis(
    manual_path, automatic_path, patient_ids, save_path=None, non_parametric=False
):
    annotations = pd.read_excel(manual_path)
    predictions = pd.read_excel(automatic_path)

    annotations = annotations[annotations["id"].isin(patient_ids)]
    predictions = predictions[predictions["id"].isin(patient_ids)]

    merged = pd.merge(annotations, predictions, on="id", suffixes=("_ann", "_pred"))

    index_columns = [col for col in predictions.columns if col not in ["id", "path"]]

    if save_path is not None:
        os.makedirs(save_path, exist_ok=True)

    stats = []

    for col in index_columns:
        ann_col = f"{col}_ann"
        pred_col = f"{col}_pred"

        if col == "tapsefw":
            title = "TAPSEfw"
            unit = "mm"
        elif col == "tapsesep":
            title = "TAPSEsep"
            unit = "mm"
        elif col == "rvfac":
            title = "RVFAC"
            unit = "%"
        elif col == "rvad":
            title = "RVDA"
            unit = r"cm$^2$"
        elif col == "rvas":
            title = "RVSA"
            unit = r"cm$^2$"
        elif col == "rvldfw":
            title = "DRVLfw"
            unit = "mm"
        elif col == "rvldsep":
            title = "DRVLsep"
            unit = "mm"
        elif col == "rvlsfw":
            title = "SRVLfw"
            unit = "mm"
        elif col == "rvlssep":
            title = "SRVLsep"
            unit = "mm"
        elif col == "tadd":
            title = "TADD"
            unit = "mm"
        elif col == "tasd":
            title = "TASD"
            unit = "mm"
        elif col == "rvldmid":
            title = "DRVLmid"
            unit = "mm"
        elif col == "rvlsmid":
            title = "SRVLmid"
            unit = "mm"
        elif col == "rvlsffw":
            title = "RVLSFfw"
            unit = "%"
        elif col == "rvlsfsep":
            title = "RVLSFsep"
            unit = "%"
        elif col == "rvlsfmid":
            title = "RVLSFmid"
            unit = "%"
        elif col == "rvlsfglobal":
            title = "RVLSFglobal"
            unit = "%"

        if ann_col not in merged.columns or pred_col not in merged.columns:
            continue

        x = merged[[ann_col, pred_col]].dropna()
        mean = x.mean(axis=1)
        diff = x[ann_col] - x[pred_col]

        perc_error = (diff.abs() / x[ann_col]).abs() * 100
        mean_perc_error = perc_error.mean()

        std_diff = diff.std()
        var_diff = diff.var()

        if non_parametric:
            center_val = diff.median()
            loa_lower = np.percentile(diff, 5)
            loa_upper = np.percentile(diff, 95)
            upper_label = "95th Perc."
            lower_label = "5th Perc."
        else:
            center_val = diff.mean()
            loa_upper = center_val + 1.96 * std_diff
            loa_lower = center_val - 1.96 * std_diff
            upper_label = "+1.96 SD"
            lower_label = "−1.96 SD"

        # Correlation
        try:
            corr, pi_pearson = pearsonr(x[ann_col], x[pred_col])
            spearman_corr, pi_spearman = spearmanr(x[ann_col], x[pred_col])
        except Exception:
            corr = float("nan")

        stats.append(
            {
                "Index": col,
                "Mean Error": center_val,
                "Variance of Error": var_diff,
                "Std Dev of Error": std_diff,
                "95% LoA Lower": loa_lower,
                "95% LoA Upper": loa_upper,
                "Mean % Error": mean_perc_error,
                "Pearson r": corr,
                "Pearson p-value": pi_pearson,
                "Spearman r": spearman_corr,
                "Spearman p-value": pi_spearman,
                "Mean value": mean.mean(),
            }
        )

        # Bland-Altman plot
        plt.figure(figsize=(6, 4))
        plt.scatter(mean, diff, alpha=0.6)
        plt.axhline(center_val, color="blue", linestyle="--")
        plt.axhline(loa_upper, color="red", linestyle=":")
        plt.axhline(loa_lower, color="red", linestyle=":")

        # Add +1.96 SD / -1.96 SD labels
        plt.text(
            mean.min(),
            loa_upper,
            upper_label,
            color="red",
            va="bottom",
            ha="left",
            fontsize=8,
        )
        plt.text(
            mean.min(),
            loa_lower,
            lower_label,
            color="red",
            va="top",
            ha="left",
            fontsize=8,
        )

        # Add margin beyond the limits of agreement
        y_margin = 0.3 * (loa_upper - loa_lower)
        plt.ylim(loa_lower - y_margin, loa_upper + y_margin)

        # plt.title(f'Bland-Altman Plot for {title}')
        plt.xlabel(f"Mean of Annotation and Prediction ({unit})")
        plt.ylabel(f"Difference (Annotation - Prediction) ({unit})")
        plt.grid(True)
        plt.tight_layout()

        if save_path:
            output_file = os.path.join(save_path, f"{col}.pdf")
            try:
                plt.savefig(output_file)
            except Exception as e:
                fallback_file = os.path.join(save_path, f"{col}.png")
                plt.savefig(fallback_file)
                print(
                    f"Warning: Couldn't save {col}.pdf, saved as PNG instead. Error: {e}"
                )
            plt.close()
        else:
            plt.show()

    # TAPSE calculation and plot
    try:
        title = "TAPSEglobal"
        unit = "mm"

        merged["tapse_ann"] = merged[["tapsefw_ann", "tapsesep_ann"]].mean(axis=1)
        merged["tapse_pred"] = merged[["tapsefw_pred", "tapsesep_pred"]].mean(axis=1)

        x = merged[["tapse_ann", "tapse_pred"]].dropna()
        mean = x.mean(axis=1)
        diff = x["tapse_ann"] - x["tapse_pred"]

        perc_error = (diff.abs() / x["tapse_ann"].abs()) * 100
        mean_perc_error = perc_error.mean()

        std_diff = diff.std()
        var_diff = diff.var()

        if non_parametric:
            center_val = diff.median()
            loa_lower = np.percentile(diff, 5)
            loa_upper = np.percentile(diff, 95)
            upper_label = "95th Perc."
            lower_label = "5th Perc."
        else:
            center_val = diff.mean()
            loa_upper = center_val + 1.96 * std_diff
            loa_lower = center_val - 1.96 * std_diff
            upper_label = "+1.96 SD"
            lower_label = "−1.96 SD"

        try:
            corr, pi_pearson = pearsonr(x["tapse_ann"], x["tapse_pred"])
            spearman_corr, pi_spearman = spearmanr(x["tapse_ann"], x["tapse_pred"])
        except Exception:
            corr = float("nan")

        stats.append(
            {
                "Index": "tapse",
                "Mean Error": center_val,
                "Variance of Error": var_diff,
                "Std Dev of Error": std_diff,
                "95% LoA Lower": loa_lower,
                "95% LoA Upper": loa_upper,
                "Mean % Error": mean_perc_error,
                "Pearson r": corr,
                "Pearson p-value": pi_pearson,
                "Spearman r": spearman_corr,
                "Spearman p-value": pi_spearman,
                "Mean value": mean.mean(),
            }
        )

        # Bland-Altman plot
        plt.figure(figsize=(6, 4))
        plt.scatter(mean, diff, alpha=0.6)
        plt.axhline(center_val, color="blue", linestyle="--")
        plt.axhline(loa_upper, color="red", linestyle=":")
        plt.axhline(loa_lower, color="red", linestyle=":")

        # Add +1.96 SD / -1.96 SD labels
        plt.text(
            mean.min(),
            loa_upper,
            upper_label,
            color="red",
            va="bottom",
            ha="left",
            fontsize=8,
        )
        plt.text(
            mean.min(),
            loa_lower,
            lower_label,
            color="red",
            va="top",
            ha="left",
            fontsize=8,
        )

        # Add margin beyond the limits of agreement
        y_margin = 0.3 * (loa_upper - loa_lower)
        plt.ylim(loa_lower - y_margin, loa_upper + y_margin)

        # plt.title(f'Bland-Altman Plot for {title}')
        plt.xlabel(f"Mean of Annotation and Prediction ({unit})")
        plt.ylabel(f"Difference (Annotation - Prediction) ({unit})")
        plt.grid(True)
        plt.tight_layout()

        if save_path:
            output_file = os.path.join(save_path, "tapse.pdf")
            try:
                plt.savefig(output_file)
            except Exception as e:
                fallback_file = os.path.join(save_path, "tapse.png")
                plt.savefig(fallback_file)
                print(
                    f"Warning: Couldn't save tapse.pdf, saved as PNG instead. Error: {e}"
                )
            plt.close()
        else:
            plt.show()
    except KeyError as e:
        print(f"Skipping TAPSE plot: missing column - {e}")

    # Save stats to Excel
    if save_path:
        stats_df = pd.DataFrame(stats)
        stats_file = os.path.join(save_path, "bland_altman_stats.xlsx")
        stats_df.to_excel(stats_file, index=False)

        # Save per-patient differences
    if save_path:
        diff_data = {"id": merged["id"]}
        for col in index_columns:
            ann_col = f"{col}_ann"
            pred_col = f"{col}_pred"
            if ann_col in merged.columns and pred_col in merged.columns:
                diff_data[f"{col}_diff"] = merged[ann_col] - merged[pred_col]
                diff_data[f"{col}_perc_error"] = (
                    (merged[ann_col] - merged[pred_col]).abs() / merged[ann_col]
                ).abs() * 100
        # Add TAPSE diff if both parts exist
        if "tapse_ann" in merged.columns and "tapse_pred" in merged.columns:
            diff_data["tapse_diff"] = merged["tapse_ann"] - merged["tapse_pred"]
            diff_data["tapse_perc_error"] = (
                (merged["tapse_ann"] - merged["tapse_pred"]).abs() / merged["tapse_ann"]
            ).abs() * 100

        per_patient_diff_df = pd.DataFrame(diff_data)
        per_patient_diff_file = os.path.join(save_path, "per_patient_differences.xlsx")
        per_patient_diff_df.to_excel(per_patient_diff_file, index=False)

        # === Save cleaned predictions ===
    try:
        # Reload predictions to avoid accidental modification of merged dataframe
        preds = pd.read_excel(automatic_path)

        # Drop columns used only for internal strain calculations
        cols_to_drop = [
            "rvlsfw (only for rv strain calculation)",
            "rvldfw (only for rv strain calculation)",
            "path",
        ]
        preds = preds.drop(columns=[c for c in cols_to_drop if c in preds.columns])

        # Save cleaned predictions file next to the original
        pred_out_path = os.path.join(
            os.path.dirname(automatic_path), "predictions.xlsx"
        )
        preds.to_excel(pred_out_path, index=False)
        print(f"Saved cleaned predictions file at: {pred_out_path}")

    except Exception as e:
        print(f"Error while creating predictions.xlsx: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Bland-Altman analysis")

    # to avoid any errors, and to possibly automatize the porocess for many acquisitions,
    # the path of the predictions should be specified as an argument
    parser.add_argument(
        "--automatic_path",
        required=True,
        help="Path to automatic predictions Excel file",
    )
    # switch. if passed it doesn't calculate bland-altman plots but rather a
    parser.add_argument(
        "--non_parametric",
        action="store_true",
        help="Calculate median and 5-95 percentiles",
    )
    args = parser.parse_args()

    manual_path = r"c:\Users\User\Desktop\maesurements_jinyang.xlsx"

    # ids of the analyzed patients
    # this was needed because not all the annotated patients were of the test set, only 10 out of 15
    # remove if not needed
    patient_ids = [100, 111, 140, 149, 160, 170, 190, 198, 199, 920]

    # saves results in the same folder where the excel with the predictions were
    # this file should be named best_unet.xlsx
    save_path = args.automatic_path.replace("best_unet.xlsx", "")

    # call of the function
    analysis(
        manual_path,
        args.automatic_path,
        patient_ids,
        save_path,
        non_parametric=args.non_parametric,
    )
